version: "3.9"

volumes:
  movies:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /films

  series:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /tv

  downloads:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /downloads

  documentaries:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /documentaries

  music:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /music

networks: 
  vpnnet: 
    driver: bridge

services:

  vpn:
    container_name: vpn
    replicas: 1
    image: dperson/openvpn-client:latest
    cap_add:
      - net_admin # required to modify network interfaces
    restart: unless-stopped
    volumes:
      - /dev/net:/dev/net:z # tun device
      - ./config/vpn:/vpn # OpenVPN configuration
    security_opt:
      - label:disable
    ports:
      - 8112:8112 # deluge webui 
      - 55555:55555 # deluge thin-client
      - 3128:3128 # squid
      - 8118:8118 # privoxy
      - 6881:6881/udp # bittorrent
      - 9091:9091 # transmission webui 
      - 51413:51413 # transmission thin-client
      - 9117:9117 # jacket
      - 7878:7878 # radarr
      - 7879:7879 # documentaries
      - 8989:8989 # sonarr
      - 8090:80 # organizr
      - 8686:8686 # lidarr
      - 6767:6767 # bazarr
      - 8265:8265 # tdarr
      - 8266:8266 # tdarr
    networks:
      - vpnnet
    command: '-f "" -d -r 192.168.0.0/24' # enable firewall and route local network traffic

  deluge:
    container_name: deluge
    replicas: 1
    image: deluge
    restart: unless-stopped
    network_mode: service:vpn # run on the vpn network
    build:
      context: ./config/deluge
    env_file: .env
    volumes:
      - downloads:/downloads # downloads folder
      - series:/tv # tv shows folder
      - movies:/movies # tv shows folder
      - documentaries:/documentaries # documentaries
      - music:/music # music
      - ./config/deluge:/config # config files

  jackett:
    container_name: jackett
    replicas: 1
    image: linuxserver/jackett:latest
    restart: unless-stopped
    network_mode: service:vpn # run on host network namespace
    env_file: .env
    volumes:
      - downloads:/downloads # downloads folder
      - series:/tv # tv shows folder
      - movies:/movies # tv shows folder
      - documentaries:/documentaries # documentaries
      - music:/music # music
      - ./config/jackett:/config # config files

  sonarr:
    container_name: sonarr
    replicas: 1
    image: linuxserver/sonarr:develop
    restart: unless-stopped
    network_mode: service:vpn # run on host network namespace
    env_file: .env
    volumes:
      - downloads:/downloads # downloads folder
      - series:/tv # tv shows folder
      - movies:/movies # tv shows folder
      - documentaries:/documentaries # documentaries
      - music:/music # music
      - ./config/sonarr:/config # config files

  radarr:
    container_name: radarr
    replicas: 1
    image: linuxserver/radarr:nightly
    restart: unless-stopped
    network_mode: service:vpn # run on host network namespace
    env_file: .env
    volumes:
      - downloads:/downloads # downloads folder
      - series:/tv # tv shows folder
      - movies:/movies # tv shows folder
      - documentaries:/documentaries # documentaries
      - music:/music # music
      - ./config/radarr:/config # config files

  documentaries:
    container_name: documentaries
    replicas: 1
    image: linuxserver/radarr:nightly
    restart: unless-stopped
    network_mode: service:vpn # run on host network namespace
    env_file: .env
    volumes:
      - downloads:/downloads # downloads folder
      - series:/tv # tv shows folder
      - movies:/movies # tv shows folder
      - documentaries:/documentaries # documentaries
      - music:/music # music
      - ./config/documentaries:/config # config files
  
  privoxy:
    container_name: privoxy
    replicas: 1
    image: ajoergensen/privoxy:latest
    restart: unless-stopped
    network_mode: service:vpn # run on the vpn network
    env_file: .env
    volumes:
      - ./config/privoxy:/etc/privoxy # config files

  squid:
    container_name: squid
    replicas: 1
    image: minimum2scp/squid:latest
    restart: unless-stopped
    network_mode: service:vpn # run on the vpn network
    env_file: .env
    volumes:
      - ./config/squid/logs:/var/log/squid # config files
      - ./config/squid/cache:/var/cache/squid # config files
      - ./config/squid/:/etc/squid # config files

  organizr:
    container_name: organizr
    replicas: 1
    image: organizr/organizr
    restart: unless-stopped
    network_mode: service:vpn # run on host network namespace
    env_file: .env
    volumes:
      - downloads:/downloads # downloads folder
      - series:/tv # tv shows folder
      - movies:/movies # tv shows folder
      - documentaries:/documentaries # documentaries
      - music:/music # music
      - ./config/organizr:/config # config files
      
  lidarr:
    container_name: lidarr
    replicas: 1
    image: lscr.io/linuxserver/lidarr
    env_file: .env
    network_mode: service:vpn # run on host network namespace
    volumes:
      - downloads:/downloads # downloads folder
      - series:/tv # tv shows folder
      - movies:/movies # tv shows folder
      - documentaries:/documentaries # documentaries
      - music:/music # music
      - ./config/lidarr:/config
    restart: unless-stopped
    
  bazarr:
    container_name: bazarr
    replicas: 0
    image: lscr.io/linuxserver/bazarr
    env_file: .env
    network_mode: service:vpn # run on host network namespace
    volumes:
      - downloads:/downloads # downloads folder
      - series:/tv # tv shows folder
      - movies:/movies # tv shows folder
      - documentaries:/documentaries # documentaries
      - music:/music # music
      - ./config/bazarr:/config
    restart: unless-stopped
    
  tdarr:
    container_name: tdarr
    replicas: 0
    image: haveagitgat/tdarr
    env_file: .env
    network_mode: service:vpn # run on host network namespace
    volumes:
      - downloads:/downloads # downloads folder
      - series:/tv # tv shows folder
      - movies:/movies # tv shows folder
      - documentaries:/documentaries # documentaries
      - music:/music # music
      - ./config/tdarr:/config
    restart: unless-stopped     

  plex:
    container_name: plex
    image: linuxserver/plex:latest
    restart: unless-stopped
    network_mode: host # run on host network namespace
    env_file: .env
    volumes:
      - ./config/plex:/config # config files
      - downloads:/downloads # downloads folder
      - series:/tv # tv shows folder
      - movies:/movies # tv shows folder
      - documentaries:/documentaries # documentaries
      - music:/music # music

  traktarr:
    container_name: traktarr
    replicas: 1
    image: traktarr
    env_file: .env
    build:
      context: ./config/traktarr
    network_mode: service:vpn # run on host network namespace
    volumes:
      - ./config/traktarr:/traktarr
      - ./config/traktarr/config:/config
    restart: unless-stopped
    
  tools:
    container_name: tools
    replicas: 1
    image: tools
    env_file: .env
    build:
      context: ./config/tools
    network_mode: service:vpn # run on host network namespace
    volumes:
      - downloads:/downloads # downloads folder
      - series:/tv # tv shows folder
      - movies:/movies # tv shows folder
      - documentaries:/documentaries # documentaries
      - music:/music # music
      - ./config/tools:/tools
      - ~/.local/share/gvfs-metadata:/root/.local/share/gvfs-metadata
      - ~/.cache/thumbnails:/root/.cache/thumbnails   
    restart: unless-stopped

  calibre:
    container_name: calibre
    replicas: 0
    image: ghcr.io/linuxserver/calibre
    restart: unless-stopped
    network_mode: host # run on host network namespace
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - GUAC_USER=abc #optional
      - GUAC_PASS=900150983cd24fb0d6963f7d28e17f72 #optional
      - UMASK_SET=022 #optional
      - CLI_ARGS= #optional
    volumes:
      - ./config/calibre:/config
    ports:
      - 8080:8080
      - 8081:8081
    restart: unless-stopped

  transmission:
    image: linuxserver/transmission
    replicas: 0
    container_name: transmission
    restart: unless-stopped
    network_mode: service:vpn # run on the vpn network
    env_file: .env
    volumes:
      - downloads:/downloads # downloads folder
      - series:/tv # tv shows folder
      - movies:/movies # tv shows folder
      - ./config/transmission:/config # config files

  rutorrent:
    container_name: rutorrent
    replicas: 0
    image: linuxserver/rutorrent:latest
    restart: unless-stopped
    network_mode: service:vpn # run on the vpn network
    env_file: .env
    volumes:
      - downloads:/downloads # downloads folder
      - ./config/rutorrent:/config # config files