version: "3.9"

volumes:
  movies:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /films

  series:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /tv

  anime:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /anime

  downloads:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /downloads

  documentaries:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /documentaries

  music:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /music

  home:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./home

  books:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /books

  comics:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /comics

networks: 
  vpnnet: 
    driver: bridge

services:

  vpn:
    container_name: vpn
    scale: 1
    image: dperson/openvpn-client:latest
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
      net.ipv4.conf.all.forwarding: 1
      net.ipv6.conf.all.forwarding: 1
    cap_add:
      - net_admin # required to modify network interfaces
    restart: unless-stopped
    volumes:
      - /dev/net:/dev/net:z # tun device
      - ./config/vpn:/vpn # OpenVPN configuration
      - home:/data # home
    security_opt:
      - label:disable
    ports:
      - 8112:8112   # deluge webui 
      - 55555:55555 # deluge thin-client    
      - 3128:3128   # squid
      - 8118:8118   # privoxy
      - 9117:9117   # jacket
      - 7878:7878   # radarr
      - 8989:8989   # sonarr
      - 8686:8686   # lidarr
      - 6767:6767   # bazarr
      - 8265:8265   # tdarr
      - 8266:8266   # tdarr
      - 32400:32400 # plex
      # - 9134:9134   # organizr
      # - 8090:8090 # mylar3
      # - 8080:8080 # calibre
      # - 8081:8081 # calibre
      # - 5299:5299 # librarian
      # - 8787:8787 #readarr
      # - 6881:6881/udp # bittorrent
      # - 9091:9091 # transmission webui 
      # - 51413:51413 # transmission thin-client
      # - 7879:7879 # documentaries
    networks:
      - vpnnet
    command: '-f "" -d -r 192.168.0.0/24' # enable firewall and route local network traffic

  deluge:
    container_name: deluge
    scale: 1
    image: deluge
    restart: unless-stopped
    network_mode: service:vpn # run on the vpn network
    build:
      context: ./config/deluge
    env_file: .env
    volumes:
      - downloads:/downloads # downloads folder
      - series:/tv # tv shows folder
      - movies:/movies # tv shows folder
      - documentaries:/documentaries # documentaries
      - music:/music # music
      - ./config/deluge:/config # config files
      - home:/data # home

  jackett:
    container_name: jackett
    scale: 1
    image: linuxserver/jackett:latest
    restart: unless-stopped
    network_mode: service:vpn # run on host network namespace
    env_file: .env
    volumes:
      - downloads:/downloads # downloads folder
      - series:/tv # tv shows folder
      - movies:/movies # tv shows folder
      - documentaries:/documentaries # documentaries
      - music:/music # music
      - ./config/jackett:/config # config files
      - home:/data # home

  sonarr:
    container_name: sonarr
    scale: 1
    image: linuxserver/sonarr:develop
    restart: unless-stopped
    network_mode: service:vpn # run on host network namespace
    env_file: .env
    volumes:
      - downloads:/downloads # downloads folder
      - series:/tv # tv shows folder
      - movies:/movies # tv shows folder
      - documentaries:/documentaries # documentaries
      - music:/music # music
      - ./config/sonarr:/config # config files
      - home:/data # home

  radarr:
    container_name: radarr
    scale: 1
    image: linuxserver/radarr:develop
    restart: unless-stopped
    network_mode: service:vpn # run on host network namespace
    env_file: .env
    volumes:
      - downloads:/downloads # downloads folder
      - series:/tv # tv shows folder
      - movies:/movies # tv shows folder
      - documentaries:/documentaries # documentaries
      - music:/music # music
      - ./config/radarr:/config # config files
      - home:/data # home

  privoxy:
    container_name: privoxy
    scale: 1
    image: ajoergensen/privoxy:latest
    restart: unless-stopped
    network_mode: service:vpn # run on the vpn network
    env_file: .env
    volumes:
      - ./config/privoxy:/etc/privoxy # config files
      - home:/data # home

  squid:
    container_name: squid
    scale: 1
    image: minimum2scp/squid:latest
    restart: unless-stopped
    network_mode: service:vpn # run on the vpn network
    env_file: .env
    volumes:
      - ./config/squid/logs:/var/log/squid # config files
      - ./config/squid/cache:/var/cache/squid # config files
      - ./config/squid/:/etc/squid # config files
      - home:/data # home

  lidarr:
    container_name: lidarr
    scale: 1
    image: lscr.io/linuxserver/lidarr
    env_file: .env
    network_mode: service:vpn # run on host network namespace
    volumes:
      - downloads:/downloads # downloads folder
      - series:/tv # tv shows folder
      - movies:/movies # tv shows folder
      - documentaries:/documentaries # documentaries
      - music:/music # music
      - ./config/lidarr:/config
      - home:/data # home
    restart: unless-stopped
    
  bazarr:
    container_name: bazarr
    scale: 0
    image: lscr.io/linuxserver/bazarr
    env_file: .env
    network_mode: service:vpn # run on host network namespace
    volumes:
      - downloads:/downloads # downloads folder
      - series:/tv # tv shows folder
      - movies:/movies # tv shows folder
      - documentaries:/documentaries # documentaries
      - music:/music # music
      - ./config/bazarr:/config
      - home:/data # home
    restart: unless-stopped

  mylar3:
    container_name: mylar3
    scale: 1
    image: lscr.io/linuxserver/mylar3
    network_mode: service:vpn # run on host network namespace
    volumes:
      - ./config/mylar3:/config
      - anime:/comics
      - downloads:/downloads # downloads folder
    restart: unless-stopped
    
  tdarr:
    container_name: tdarr
    scale: 0
    image: haveagitgat/tdarr
    env_file: .env
    network_mode: service:vpn # run on host network namespace
    volumes:
      - downloads:/downloads # downloads folder
      - series:/tv # tv shows folder
      - movies:/movies # tv shows folder
      - documentaries:/documentaries # documentaries
      - music:/music # music
      - ./config/tdarr:/config
      - home:/data # home
    restart: unless-stopped     

  plex:
    container_name: plex
    image: linuxserver/plex:latest
    network_mode: service:vpn # run on host network namespace
    env_file: .env
    volumes:
      - ./config/plex:/config # config files
      - downloads:/downloads # downloads folder
      - series:/tv # tv shows folder
      - movies:/movies # tv shows folder
      - documentaries:/documentaries # documentaries
      - music:/music # music
      - home:/data # home
    restart: unless-stopped

  traktarr:
    container_name: traktarr
    scale: 1
    image: traktarr
    env_file: .env
    build:
      context: ./config/traktarr
    network_mode: service:vpn # run on host network namespace
    volumes:
      - downloads:/downloads # downloads folder
      - series:/tv # tv shows folder
      - movies:/movies # tv shows folder
      - documentaries:/documentaries # documentaries
      - music:/music # music
      - ./config/traktarr:/traktarr
      - ./config/traktarr/config:/config
      - home:/data # home
    restart: unless-stopped

  cloudflare:
    container_name: cloudflare
    scale: 1
    image: cloudflare/cloudflared:latest
    env_file: .env
    network_mode: host # run on host network namespace
    command: tunnel --no-autoupdate run --token $CF_TOKEN 
    restart: unless-stopped

  # amd:
  #   container_name: amd    
  #   scale: 0
  #   image: randomninjaatk/amd 
  #   env_file: .env
  #   network_mode: service:vpn # run on host network namespace
  #   volumes:
  #     - downloads:/downloads # downloads folder
  #     - series:/tv # tv shows folder
  #     - movies:/movies # tv shows folder
  #     - documentaries:/documentaries # documentaries
  #     - music:/music # music
  #     - ./config/amd:/config
  #     - /downloads/amd:/downloads-amd
  #     - home:/data # home
  #   restart: unless-stopped

  # calibre:
  #   container_name: calibre
  #   scale: 0
  #   image: ghcr.io/linuxserver/calibre
  #   restart: unless-stopped
  #   network_mode: service:vpn # run on host network namespace
  #   env_file: .env    
  #   volumes:
  #     - downloads:/downloads # downloads folder
  #     - series:/tv # tv shows folder
  #     - movies:/movies # tv shows folder
  #     - documentaries:/documentaries # documentaries
  #     - music:/music # music
  #     - ./config/calibre:/config
  #     - home:/data # home

  # transmission:
  #   image: linuxserver/transmission
  #   scale: 0
  #   container_name: transmission
  #   restart: unless-stopped
  #   network_mode: service:vpn # run on host network namespace
  #   env_file: .env
  #   volumes:
  #     - downloads:/downloads # downloads folder
  #     - series:/tv # tv shows folder
  #     - movies:/movies # tv shows folder
  #     - documentaries:/documentaries # documentaries
  #     - music:/music # music
  #     - ./config/transmission:/config # config files
  #     - home:/data # home

  # rutorrent:
  #   container_name: rutorrent
  #   scale: 0
  #   image: linuxserver/rutorrent:latest
  #   restart: unless-stopped
  #   network_mode: service:vpn # run on the vpn network
  #   env_file: .env
  #   volumes:
  #     - downloads:/downloads # downloads folder
  #     - series:/tv # tv shows folder
  #     - movies:/movies # tv shows folder
  #     - documentaries:/documentaries # documentaries
  #     - music:/music # music
  #     - ./config/rutorrent:/config # config files
  #     - home:/data # home

  # tools:
  #   container_name: tools
  #   scale: 1
  #   image: tools
  #   env_file: .env
  #   build:
  #     context: ./config/tools
  #   network_mode: service:vpn # run on host network namespace
  #   volumes:
  #     - downloads:/downloads # downloads folder
  #     - series:/tv # tv shows folder
  #     - movies:/movies # tv shows folder
  #     - documentaries:/documentaries # documentaries
  #     - music:/music # music
  #     - ./config/tools:/tools
  #     - ~/.local/share/gvfs-metadata:/root/.local/share/gvfs-metadata
  #     - ~/.cache/thumbnails:/root/.cache/thumbnails   
  #     - home:/data # home
  #   restart: unless-stopped

  # lazylibrarian:
  #   container_name: lazylibrarian
  #   scale: 1
  #   image: linuxserver/lazylibrarian
  #   env_file: .env
  #   network_mode: service:vpn # run on host network namespace
  #   volumes:
  #     - ./config/librarian:/config
  #     - downloads:/downloads # downloads folder
  #     - books:/books # home
  #   restart: unless-stopped

  # readarr:
  #   container_name: readarr
  #   scale: 1
  #   image: linuxserver/readarr:develop
  #   env_file: .env
  #   network_mode: service:vpn # run on host network namespace
  #   volumes:
  #     - ./config/readarr:/config
  #     - downloads:/downloads # downloads folder
  #     - books:/books # home
  #   restart: unless-stopped

  # documentaries:
  #   container_name: documentaries
  #   scale: 1
  #   image: linuxserver/radarr:nightly
  #   restart: unless-stopped
  #   network_mode: service:vpn # run on host network namespace
  #   env_file: .env
  #   volumes:
  #     - downloads:/downloads # downloads folder
  #     - series:/tv # tv shows folder
  #     - movies:/movies # tv shows folder
  #     - documentaries:/documentaries # documentaries
  #     - music:/music # music
  #     - ./config/documentaries:/config # config files
  #     - home:/data # home
  

#  organizr:
#    container_name: organizr
#    scale: 1
#    image: organizr/organizr
#    restart: unless-stopped
#    network_mode: service:vpn # run on host network namespace
#    env_file: .env
#    volumes:
#      - downloads:/downloads # downloads folder
#      - series:/tv # tv shows folder
#      - movies:/movies # tv shows folder
#      - documentaries:/documentaries # documentaries
#      - music:/music # music
#      - ./config/organizr:/config # config files
#      - home:/data # home
